name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:

    - name: Installing Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: '6.x'

    - name: Downloading code
      uses: actions/checkout@v3

    - name: Installing other dependencies
      run: |
        npm install
        npm i -g eslint
        npm i -g codecov
        wget -qO- https://download.openzim.org/release/zim-tools/zim-tools_linux-x86_64.tar.gz | tar xvz

    - name: Running ESLint
      run: npm run lint

    - name: Running tests
      run: npm run codecov
      env:
        REDIS: 'redis://127.0.0.1:6379'
        S3_URL: ${{ secrets.S3_URL }}
        ZIMCHECK_PATH: $( find .. -name zimcheck )
        ZIMDUMP_PATH: $( find .. -name zimdump )

    - name: Uploading Codecov stats
      uses: codecov/codecov-action@v3
      if: ${{ matrix.node-version == '18.x' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
