name: Docker

on:
  push:
    branches:
      - reg-test

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Build and push
        uses: openzim/docker-publish-action@v9
        with:
          image-name: openzim/mwoffliner
          tag-pattern: /^v([0-9.]+)$/
          latest-on-tag: false
          restrict-to: openzim/mwoffliner
          credentials: |
            DOCKERIO_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERIO_TOKEN=${{ secrets.DOCKERHUB_PASSWORD }}
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          manual-tag: TEST-reg
          repo_description: auto
          repo_overview: auto

